name: integration

on:
  push:
    branches: [ master ]

jobs:
  publish-aepp:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.1.0
    secrets: inherit
    with:
      FILE: ./aepp/Dockerfile
      CONTEXT: ./aepp
      BUILD_ARGS: COMMAND=stg
      DOCKERHUB_REPO: "aeternity/aepp-graffiti"
  deploy-aepp:
    needs: [publish-aepp]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.1.0
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: aepp-graffiti
      DEPLOY_VERSION: ${{ github.ref_name }}
      DEPLOY_SUBDOMAIN: graffiti
  publish-server:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.1.0
    secrets: inherit
    with:
      FILE: ./server/Dockerfile
      CONTEXT: ./server
      DOCKERHUB_REPO: "aeternity/graffiti-server"
  deploy-server-testnet:
    needs: [publish-server]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.1.0
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: graffiti-server-testnet
      DEPLOY_VERSION: ${{ github.ref_name }}
