name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  publish-aepp:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.1.0
    secrets: inherit
    with:
      FILE: ./aepp/Dockerfile
      CONTEXT: ./aepp
      BUILD_ARGS: |
        COMMAND=stg
        MAINNET_SERVER_URL=https://graffiti-server-mainnet.stg.aepps.com
        TESTNET_SERVER_URL=https://pr-${{ github.event.number }}-graffiti-server-testnet.stg.aepps.com
      DOCKERHUB_REPO: "aeternitybot/aepp-graffiti"
  deploy-aepp:
    needs: [publish-aepp]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.1.0
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: aepp-graffiti
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-graffiti"
  publish-server:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.1.0
    secrets: inherit
    with:
      FILE: ./server/Dockerfile
      CONTEXT: ./server
      DOCKERHUB_REPO: "aeternitybot/graffiti-server"
  deploy-server-testnet:
    needs: [publish-server]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.1.0
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: graffiti-server-testnet
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-graffiti-server-testnet"
