name: pull-request-cleanup

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  rollback-aepp:
    uses: aeternity/github-actions/.github/workflows/_rollback-gitops.yml@v2.3.1
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: aepp-graffiti
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-graffiti"
  delete-tag-aepp:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-ecr.yml@v2.3.1
    secrets: inherit
    with:
      REPOSITORY: "aepp-graffiti"
      TAG: "pr-${{ github.event.number }}"
  rollback-server:
    uses: aeternity/github-actions/.github/workflows/_rollback-gitops.yml@v2.3.1
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: graffiti-server-testnet
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-graffiti-server-testnet"
  delete-tag-server:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-ecr.yml@v2.3.1
    secrets: inherit
    with:
      REPOSITORY: "graffiti-server"
      TAG: "pr-${{ github.event.number }}"
