name: release-server

on:
  push:
    tags: [ "graffiti-server-v*" ]

jobs:
  publish-server:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.2.0
    secrets: inherit
    with:
      FILE: ./server/Dockerfile
      CONTEXT: ./server
      DOCKERHUB_REPO: "aeternity/graffiti-server"
  deploy-server-testnet:
    needs: [publish-server]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.2.0
    secrets: inherit
    with:
      DEPLOY_ENV: prd
      DEPLOY_APP: graffiti-server-testnet
      DEPLOY_TAG: ${{ github.ref_name }}
  deploy-server-mainnet:
    needs: [publish-server, deploy-server-testnet]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.2.0
    secrets: inherit
    with:
      DEPLOY_ENV: prd
      DEPLOY_APP: graffiti-server-mainnet
      DEPLOY_TAG: ${{ github.ref_name }}
